### ISSUE TITLE
Add another step

### ISSUE THREAD

**Issue by iwasthesword** [monstar-lab-oss/honkit-ghpages-action#1]
I need to run a NPM script before I can generate my honkit book, is there a way to do this using this action?
I tried adding another step: 
```
    steps:
      - name: Fetch snapshot
        run: npm run build
      - name: Build and deploy
        uses: monstar-lab-oss/honkit-ghpages-action@main
```

but it gives me an error saying NPM can't find the package.json.
